// rsrc-tool: developer utility for StuntCopter's classic resources.
//
//   rsrc-tool extract <AppleDouble file> <out.rsrc>   pull the resource fork out of "._name"
//   rsrc-tool list    <file.rsrc>                     list resources
//   rsrc-tool embed   <file> <out.swift> <EnumName>   generate a Swift source embedding a file
//   rsrc-tool dump    <file.rsrc> <outdir>            PICT/RGN/ICON/ICN# as PNGs
//   rsrc-tool iconset <file.rsrc> <out.iconset>       AppIcon.iconset from ICN# 129

import ClassicToolbox
import CoreGraphics
import Foundation
import ImageIO
import UniformTypeIdentifiers

func fail(_ msg: String) -> Never {
    FileHandle.standardError.write(Data((msg + "\n").utf8))
    exit(1)
}

func readBytes(_ path: String) -> [UInt8] {
    guard let d = FileManager.default.contents(atPath: path) else { fail("can't read \(path)") }
    return [UInt8](d)
}

/// Writes a bitmap as PNG, scaled by an integer factor. `mask` (if given) makes
/// unmasked pixels transparent.
func writePNG(_ bm: BitMap, to path: String, scale: Int = 1, mask: BitMap? = nil) {
    let w = bm.width * scale, h = bm.height * scale
    var rgba = [UInt8](repeating: 0, count: w * h * 4)
    for y in 0..<h {
        for x in 0..<w {
            let sx = x / scale, sy = y / scale
            let on = bm.pixels[sy * bm.width + sx] != 0
            let visible = mask.map { $0.pixels[sy * $0.width + sx] != 0 } ?? true
            let i = (y * w + x) * 4
            let v: UInt8 = on ? 0 : 255
            rgba[i] = v; rgba[i + 1] = v; rgba[i + 2] = v
            rgba[i + 3] = visible ? 255 : 0
        }
    }
    let provider = CGDataProvider(data: Data(rgba) as CFData)!
    let image = CGImage(width: w, height: h, bitsPerComponent: 8, bitsPerPixel: 32, bytesPerRow: w * 4,
                        space: CGColorSpaceCreateDeviceRGB(),
                        bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.premultipliedLast.rawValue),
                        provider: provider, decode: nil, shouldInterpolate: false, intent: .defaultIntent)!
    let url = URL(fileURLWithPath: path) as CFURL
    guard let dest = CGImageDestinationCreateWithURL(url, UTType.png.identifier as CFString, 1, nil) else {
        fail("can't write \(path)")
    }
    CGImageDestinationAddImage(dest, image, nil)
    CGImageDestinationFinalize(dest)
}

func writeRGBAPNG(_ rgba: [UInt8], size: Int, to path: String) {
    let provider = CGDataProvider(data: Data(rgba) as CFData)!
    let image = CGImage(width: size, height: size, bitsPerComponent: 8, bitsPerPixel: 32, bytesPerRow: size * 4,
                        space: CGColorSpaceCreateDeviceRGB(),
                        bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.premultipliedLast.rawValue),
                        provider: provider, decode: nil, shouldInterpolate: false, intent: .defaultIntent)!
    let dest = CGImageDestinationCreateWithURL(URL(fileURLWithPath: path) as CFURL, UTType.png.identifier as CFString, 1, nil)!
    CGImageDestinationAddImage(dest, image, nil)
    CGImageDestinationFinalize(dest)
}

@MainActor func render(_ pic: Picture) -> BitMap {
    let frame = pic.picFrame.offsetBy(-pic.picFrame.left, -pic.picFrame.top)
    let qd = QuickDraw(port: GrafPort(size: frame))
    qd.DrawPicture(pic, frame)
    return qd.thePort.portBits
}

@MainActor func render(_ rgn: Region) -> BitMap {
    let bbox = rgn.rgnBBox
    let qd = QuickDraw(port: GrafPort(size: bbox.offsetBy(-bbox.left, -bbox.top)))
    let r = Region()
    r.copy(from: rgn)
    r.offset(-bbox.left, -bbox.top)
    qd.PaintRgn(r)
    return qd.thePort.portBits
}

let args = CommandLine.arguments
guard args.count >= 3 else {
    fail("usage: rsrc-tool extract|list|embed|dump|iconset <input> [output]")
}

switch args[1] {
case "extract":
    guard args.count == 4 else { fail("usage: rsrc-tool extract <AppleDouble> <out.rsrc>") }
    let fork = try ResourceFork.resourceForkData(fromAppleDouble: readBytes(args[2]))
    _ = try ResourceFork(forkData: fork)   // validate
    try Data(fork).write(to: URL(fileURLWithPath: args[3]))
    print("wrote \(fork.count) bytes to \(args[3])")

case "list":
    let fork = try ResourceFork(forkData: readBytes(args[2]))
    for e in fork.entries {
        print("'\(e.type)' \(String(e.id).padding(toLength: 6, withPad: " ", startingAt: 0)) \(String(e.data.count).padding(toLength: 7, withPad: " ", startingAt: 0)) \(e.name ?? "")")
    }

case "embed":
    guard args.count == 5 else { fail("usage: rsrc-tool embed <file> <out.swift> <EnumName>") }
    let bytes = readBytes(args[2])
    let name = URL(fileURLWithPath: args[2]).lastPathComponent
    let b64 = Data(bytes).base64EncodedString(options: [.lineLength76Characters, .endLineWithLineFeed])
    let src = """
    // Generated by `rsrc-tool embed` from Resources/\(name) — do not edit.

    enum \(args[4]) {
        static let base64 = \"\"\"
    \(b64)
    \"\"\"
    }

    """
    try src.write(toFile: args[3], atomically: true, encoding: .utf8)
    print("wrote \(args[3]) (\(bytes.count) bytes embedded)")

case "dump":
    guard args.count == 4 else { fail("usage: rsrc-tool dump <file.rsrc> <outdir>") }
    let fork = try ResourceFork(forkData: readBytes(args[2]))
    let out = args[3]
    try FileManager.default.createDirectory(atPath: out, withIntermediateDirectories: true)
    for e in fork.entries {
        let base = "\(out)/\(e.type.trimmingCharacters(in: .whitespaces))_\(e.id)"
        switch e.type {
        case "PICT": writePNG(render(try fork.picture(e.id)), to: base + ".png", scale: 2)
        case "RGN ": writePNG(render(try fork.region(e.id)), to: base + ".png", scale: 2)
        case "ICON": writePNG(try fork.icon(e.id), to: base + ".png", scale: 4)
        case "ICN#":
            let (icon, mask) = try fork.iconList(e.id)
            writePNG(icon, to: base + ".png", scale: 4, mask: mask)
        default: continue
        }
        print("wrote \(base).png")
    }

case "iconset":
    guard args.count == 4 else { fail("usage: rsrc-tool iconset <file.rsrc> <out.iconset>") }
    let fork = try ResourceFork(forkData: readBytes(args[2]))
    let (icon, _) = try fork.iconList(129)   // the ICN# "mask" isn't a real mask; see appIconPixels
    let out = args[3]
    try FileManager.default.createDirectory(atPath: out, withIntermediateDirectories: true)
    for size in [16, 32, 128, 256, 512] {
        for retina in [1, 2] {
            let px = size * retina
            let name = retina == 1 ? "icon_\(size)x\(size).png" : "icon_\(size)x\(size)@2x.png"
            writeRGBAPNG(appIconPixels(icon: icon, size: px), size: px, to: "\(out)/\(name)")
        }
    }
    print("wrote \(out)")

default:
    fail("unknown command \(args[1])")
}
